<%@page pageEncoding="UTF-8"%>
<div id="header" style="width:100%;height:78px;line-height:78px;background:linear-gradient(#0081c2,#0595dd);"> 
			<img src="../img/logo.png"/>
			<span style="font-size:21px;font-family:'微软雅黑';color:#fff;margin-left:110px;letter-spacing:2px;">电商平台后台管理系统</span>
</div>
<style>
img {
	width:80px;
	height:40px;
	position:absolute;
	top:25%;
	margin-left:30px;
}
</style>