/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-06-13 08:17:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class userManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/inc/nav.inc", Long.valueOf(1560413107348L));
    _jspx_dependants.put("/admin/inc/user/user_dialog.inc", Long.valueOf(1560398601452L));
    _jspx_dependants.put("/admin/inc/header.inc", Long.valueOf(1557759034591L));
    _jspx_dependants.put("/admin/inc/user/user_field.inc", Long.valueOf(1560406164378L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../easyui/themes/bootstrap/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../easyui/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../easyui/demo/demo.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../easyui/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<title>电商平台后台管理系统</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t<div data-options=\"region:'north'\"\r\n");
      out.write("\t\t\tstyle=\"height: 80px; width: 100%;\">\r\n");
      out.write("\t\t\t<!-- html中的引入文件 -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"header\" style=\"width:100%;height:78px;line-height:78px;background:linear-gradient(#0081c2,#0595dd);\"> \r\n");
      out.write("\t\t\t<img src=\"../img/logo.png\"/>\r\n");
      out.write("\t\t\t<span style=\"font-size:21px;font-family:'微软雅黑';color:#fff;margin-left:110px;letter-spacing:2px;\">电商平台后台管理系统</span>\r\n");
      out.write("</div>\r\n");
      out.write("<style>\r\n");
      out.write("img {\r\n");
      out.write("\twidth:80px;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:25%;\r\n");
      out.write("\tmargin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 左侧导航 -->\r\n");
      out.write("\t\t<div data-options=\"region:'west'\" title='功能导航' style=\"width: 200px;\">\r\n");
      out.write("\t\t\t");
 String panelIndex=request.getParameter("panelIndex");
      out.write("\r\n");
      out.write("<div class=\"easyui-accordion\" style=\"width:100%;\">\r\n");
      out.write("\t<div title=\"引导页管理\" id=\"advert\" ");
if("0".equals(panelIndex)){
      out.write(" data-options=\"selected:true\"");
}
      out.write(">\r\n");
      out.write("\t\t<a href=\"guideManage.jsp?panelIndex=0\"  class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-large-smartart'\" style=\"width:100%;text-align:left;margin-top:5px;\">引导管理</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div title=\"首页管理\" id=\"homepage\" ");
if("1".equals(panelIndex)){
      out.write(" data-options=\"selected:true\"");
}
      out.write(">\r\n");
      out.write("\t<a href=\"advertManage.jsp?panelIndex=1\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-tip'\" style=\"width:100%;text-align:left;margin-top:5px;\">广告管理</a>\r\n");
      out.write("\t<a href=\"promotionManage.jsp?panelIndex=1\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-print'\" style=\"width:100%;text-align:left;margin-top:5px;\">推荐管理</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div title=\"分类管理\" id=\"guidepage\" ");
if("2".equals(panelIndex)){
      out.write(" data-options=\"selected:true\"");
}
      out.write(">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div title=\"商品管理\" id=\"commodity\" ");
if("3".equals(panelIndex)){
      out.write(" data-options=\"selected:true\"");
}
      out.write(">\r\n");
      out.write("\t<a href=\"commodityManage.jsp?panelIndex=1\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-tip'\" style=\"width:100%;text-align:left;margin-top:5px;\">产品管理</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div title=\"用户管理\" id=\"user\" ");
if("4".equals(panelIndex)){
      out.write(" data-options=\"selected:true\"");
}
      out.write(">\r\n");
      out.write("\t<a href=\"userManage.jsp?panelIndex=1\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-tip'\" style=\"width:100%;text-align:left;margin-top:5px;\">用户管理</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<style>\r\n");
      out.write(" #advert a:visited{ \r\n");
      out.write("\tbackground-color:yellow;\r\n");
      out.write("}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 主体部分 -->\r\n");
      out.write("\t\t<div data-options=\"region:'center',title:'广告管理  | 引导管理'\">\r\n");
      out.write("\t\t\t");
      out.write("<!-- 轮播广告管理页面的数据表格 -->\r\n");
      out.write("﻿\r\n");
      out.write("<table id=\"dg_user\" class=\"easyui-datagrid\" \r\n");
      out.write("       data-options=\"singleSelect:true,fit:true,toolbar:'#tb',\r\n");
      out.write("       pagination:true,pageSize:30,pageList:[10,20,30,50,100],\r\n");
      out.write("       onHeaderContextMenu:createGridHeaderContextMenu,\r\n");
      out.write("       loadMsg:'数据正在努力加载，请稍后...'\" >\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th data-options=\"field:'selector',checkbox:true\"></th>\r\n");
      out.write("      <th data-options=\"field:'id',width:40,align:'center',hidden:true\">编号</th>\r\n");
      out.write("      <th data-options=\"field:'userName',width:200,align:'center'\">用户名</th>\r\n");
      out.write("      <th data-options=\"field:'name',width:100,align:'center'\">姓名</th>\r\n");
      out.write("      <th data-options=\"field:'sex',width:100,align:'center'\">性别</th>\r\n");
      out.write("      <th data-options=\"field:'age',width:100,align:'center'\">年纪</th>\r\n");
      out.write("      <th data-options=\"field:'address',width:350,align:'center'\">收获地址</th>\r\n");
      out.write("      <th data-options=\"field:'phone',width:200,align:'center'\">电话号码</th>\r\n");
      out.write("      <th data-options=\"field:'wealthy',width:100,align:'center'\">余额(元)</th>\r\n");
      out.write("      <th data-options=\"field:'userImg',width:350,align:'center'\">图片地址</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("﻿<!-- 工具栏 -->\r\n");
      out.write("<div id=\"tb\" style=\"padding:5px;\">\r\n");
      out.write("  <input class=\"easyui-textbox\" style=\"width:160px;\" id=\"title\" data-options=\"prompt:'区域/顺序号/商品编号'\"/>\r\n");
      out.write("  <a id=\"btn_Query\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search'\">查询</a>\r\n");
      out.write("  <a id=\"btn_Add\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">添加</a>\r\n");
      out.write("  <a id=\"btn_Edit\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-edit'\">修改</a>\r\n");
      out.write("  <a id=\"btn_Del\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\">删除</a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"dialog_user\" class=\"easyui-dialog\" data-options=\"title:'编辑广告页数据',buttons:'#btn_user',closed:true\" style=\"width:430px;height:330px;padding:20px 30px;\">\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t该功能不允许操作\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 对话框按钮 -->\r\n");
      out.write("<div id=\"btn_user\">\r\n");
      out.write("  <!-- <a id=\"a_save\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-ok'\" onclick=\"saveRecord()\">保存</a> -->\r\n");
      out.write("  <a class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-no'\" onclick=\"javascript:$('#dialog_user').dialog('close')\">退出</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"Plupload/js/plupload.full.min.js\"></script>\r\n");
      out.write("<script src=\"dist/qiniu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/util.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/user.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
